theme: jekyll-theme-slate
title: <img src="(https://github.com/AkiliKhasi/AkiliKhasi.github.io/blob/master/khlogo2-removebg-preview%20(1).png)" />
description: This website contains code samples of work that I have done to help automate daily tasks.
